# Generated by Django 3.1.3 on 2020-11-27 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blogs.extendinguser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='read_by_user',
            field=models.ManyToManyField(editable=False, to='blogs.ExtendingUser'),
        ),
    ]
