# Generated by Django 3.1.3 on 2020-11-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20201127_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendinguser',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, null=True, to='blogs.Blog'),
        ),
    ]
