# Generated by Django 3.1.3 on 2020-11-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20201127_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendinguser',
            name='subscribed_to',
            field=models.ManyToManyField(to='blogs.Blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='read_by_user',
            field=models.ManyToManyField(to='blogs.ExtendingUser'),
        ),
    ]
