# Generated by Django 3.1.3 on 2020-11-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20201128_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='read_by_user',
        ),
        migrations.AddField(
            model_name='extendinguser',
            name='read_posts',
            field=models.ManyToManyField(to='blogs.Post'),
        ),
    ]
